### ISSUE TITLE
Solution does not build from 2017

### ISSUE THREAD

**Issue by goofballLogic** [linked-data-dotnet/json-ld.net#22]
The project does not build from VS2017 (appears to be hard-wired to 2015).
Attempting the upgrade process leaves errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The TargetFramework value 'net40-client' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.	json-ld.net	C:\Program Files\dotnet\sdk\2.0.3\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	96	
Error	MSB3202	The project file "C:\src\json-ld.net\test\json-ld.net.tests\json-ld.net.tests.xproj" was not found.	json-ld.net.tests	C:\Users\andrew.gibson\AppData\Local\Temp\tmpa2e93ef2820d47cfbc8cf44fb5e8602f.proj	28	
Error	MSB4226	The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\DotNet\Microsoft.DotNet.Props" was not found. Also, tried to find "DotNet\Microsoft.DotNet.Props" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0" . These search paths are defined in "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.	json-ld.net	C:\src\json-ld.net\src\json-ld.net\json-ld.net.xproj	8	

Are you open to this solution being ported to 2017?

**Comment by goofballLogic** [comment]
Ok, so if you open the code in 2017, allow the upgrade process, then revert the git repo (while keeping studio open), you can then build using the powershell script supplied.

However, tests are failing for me:
```

    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0001", testname: "load JSON-LD document", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...], [...], [...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0002", testname: "load JSON document", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...], [...], [...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0003", testname: "load JSON document with extension-type", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...], [...], [...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0005", testname: "Load JSON-LD through 301 redirect", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = null, output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0006", testname: "Load JSON-LD through 303 redirect", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = null, output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0007", testname: "Load JSON-LD through 307 redirect", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = null, output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0009", testname: "load JSON-LD document with link", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0010", testname: "load JSON document with link", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0011", testname: "load JSON document with extension-type with link", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
  Finished:    json-ld.net.tests
=== TEST EXECUTION SUMMARY ===
   json-ld.net.tests  Total: 545, Errors: 0, Failed: 9, Skipped: 0, Time: 10.251s
Tests failed!!!
```

**Comment by goofballLogic** [comment]
It would appear these tests are failing due to "http://json-ld.org/test-suite/tests/remote-doc-0001-in.jsonld" being automatically redirected to "https://json-ld.org/test-suite/tests/remote-doc-0001-in.jsonld" by json-ld.org.

The tests for some reason use a locally cached version of the corresponding -out files (which haven't been updated). I'm not sure why it's using the remote version of -in and the local version of -out. Potential fixes:

1. Correct the local copies of the -out files to match the canonical versions
2. Change the tests to use the remote versions of both -in and -out files
3. Change the tests to use local versions of both -in and -out files

**Comment by goofballLogic** [comment]
Moving the broken tests part of this issue into a new one (for a pull request)

**Comment by xivk** [comment]
I think this will be fixed with the pull-request here:

https://github.com/linked-data-dotnet/json-ld.net/pull/37

Would it be OK to remove the `net40-client` and portable profiles as they have become obsolete? The old package will still be there for those still on those platforms.
