### ISSUE TITLE
Tests failing due to json-ld.org changes -> https

### ISSUE THREAD

**Issue by goofballLogic** [linked-data-dotnet/json-ld.net#23]
Tests which use the remote document loading feature are failing for me:
```

    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0001", testname: "load JSON-LD document", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...], [...], [...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0002", testname: "load JSON document", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...], [...], [...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0003", testname: "load JSON document with extension-type", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...], [...], [...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0005", testname: "Load JSON-LD through 301 redirect", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = null, output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0006", testname: "Load JSON-LD through 303 redirect", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = null, output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0007", testname: "Load JSON-LD through 307 redirect", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = null, output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0009", testname: "load JSON-LD document with link", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0010", testname: "load JSON document with link", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
    JsonLD.Test.ConformanceTests.ConformanceTestPasses(id: "remote-doc-manifest.jsonld#t0011", testname: "load JSON document with extension-type with link", conformanceCase: ConformanceCase { context = null, error = null, frame = null, input = [[...]], output = [[...]], ... }) [FAIL]
      Returned JSON doesn't match expectations.
      Expected: True
      Actual:   False
      Stack Trace:
        ConformanceTests.cs(34,0): at JsonLD.Test.ConformanceTests.ConformanceTestPasses(String id, String testname, ConformanceCase conformanceCase)
  Finished:    json-ld.net.tests
=== TEST EXECUTION SUMMARY ===
   json-ld.net.tests  Total: 545, Errors: 0, Failed: 9, Skipped: 0, Time: 10.251s
Tests failed!!!
```

**Comment by goofballLogic** [comment]
It would appear these tests are failing due to "http://json-ld.org/test-suite/tests/remote-doc-0001-in.jsonld" being automatically redirected to "https://json-ld.org/test-suite/tests/remote-doc-0001-in.jsonld" by json-ld.org.

The tests for some reason use a locally cached version of the corresponding -out files (which haven't been updated). I'm not sure why it's using the remote version of -in and the local version of -out. Potential fixes:

1. Correct the local copies of the -out files to match the canonical versions
2. Change the tests to use the remote versions of both -in and -out files
3. Change the tests to use local versions of both -in and -out files
