### ISSUE TITLE
Getting OutOfMemoryError while try to frame JsonLd 

### ISSUE THREAD

**Issue by a-rajasekar** [linked-data-dotnet/json-ld.net#42]
Getting OutOfMemoryError while try to frame JsonLd object using , please help me to resolve this issue 

graphToFrame type is NQUARDS

 RDFDataset dataSet = RDFDatasetUtils.parseNQuads(graphToFrame);
JsonLdOptions options = new JsonLdOptions();	
frameData = JsonUtils.fromString(frame);	
Object rval = new JsonLdApi(options).fromRDF(dataSet);
Object framedJsonObject = JsonLdProcessor.frame(rval, frameData, options);

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
at java.util.HashMap.newNode(Unknown Source)
at java.util.HashMap.putVal(Unknown Source)
at java.util.HashMap.put(Unknown Source)
at java.util.HashSet.add(Unknown Source)
at java.util.AbstractCollection.addAll(Unknown Source)
at java.util.HashSet.<init>(Unknown Source)
at com.github.jsonldjava.core.JsonLdApi.removeDependents(JsonLdApi.java:1681)
at com.github.jsonldjava.core.JsonLdApi.removeEmbed(JsonLdApi.java:1676)
at com.github.jsonldjava.core.JsonLdApi.frame(JsonLdApi.java:1456)

**Comment by asbjornu** [comment]
Seems like you've found the wrong repository, as this is for the C# implementation of JSON-LD, not Java. Perhaps it's [JSONLD Java](https://github.com/jsonld-java/jsonld-java) you're looking for?

**Comment by a-rajasekar** [comment]
Yes asbjornu ,I am looking for JSONLD Java only,shall I create new ticket in to that ?

**Comment by asbjornu** [comment]
Yes, please go to that repository and create a ticket. We have nothing to do with the Java implementation at all.
